package com.yusufsezer.repository;

import com.yusufsezer.model.Contact;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

public class DB2Repository extends SQLRepository {

    public DB2Repository(Connection connection) {
        super(connection);
    }

    @Override
    protected void createTable() {
        // String sql = "CREATE TABLE contacts ("
        //         + Contact.ID + " INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY, "
        //         + Contact.FIRST_NAME + " VARCHAR(100), "
        //         + Contact.LAST_NAME + " VARCHAR(100), "
        //         + Contact.EMAIL + " VARCHAR(100), "
        //         + Contact.PHONE_NUMBER + " VARCHAR(30), "
        //         + Contact.ADDRESS + " VARCHAR(255), "
        //         + Contact.WEB_ADDRESS + " VARCHAR(255), "
        //         + Contact.NOTES + " VARCHAR(1024))";

        String sql = "CREATE TABLE A919228.contacts (ID INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1, CACHE 20, NO CYCLE, NO ORDER, MAXVALUE 2147483647, MINVALUE 1), FIRST_NAME VARCHAR(100) FOR SBCS DATA WITH DEFAULT NULL, LAST_NAME VARCHAR(100) FOR SBCS DATA WITH DEFAULT NULL, EMAIL VARCHAR(80) FOR SBCS DATA WITH DEFAULT NULL, PHONE_NUMBER VARCHAR(30) FOR SBCS DATA WITH DEFAULT NULL, ADDRESS VARCHAR(100) FOR SBCS DATA WITH DEFAULT NULL, WEB_ADDRESS VARCHAR(255) FOR SBCS DATA WITH DEFAULT NULL, NOTES VARCHAR(100) FOR SBCS DATA WITH DEFAULT NULL, CONSTRAINT ID PRIMARY KEY (ID)) IN EMPDB.CONTACTS PARTITION BY SIZE AUDIT NONE DATA CAPTURE NONE CCSID EBCDIC NOT VOLATILE APPEND NO; COMMIT;";
        try (Statement statement = connection.createStatement()) {
            statement.execute(sql);
        } catch (SQLException exception) {
            logException(exception);
            throw new RuntimeException("Failed to create table.");
        }
    }

}
